name: explainable_classifiers
channels:
    - conda-forge
    - defaults
dependencies:
  - python=3.6
  - tensorflow=1.13
  - keras
  - pandas
  - numpy
  - nltk
  - scikit-learn
  - ipython
  - jupyter
  - lime=0.1.1.34=py_0
  - dill
